"""empty message

Revision ID: 000c68a54b17
Revises: 
Create Date: 2020-04-26 17:34:06.108555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000c68a54b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('label_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('positive_labels', sa.Integer(), nullable=True),
    sa.Column('negative_labels', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('w2v_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_files.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('w2v_models')
    op.drop_table('label_files')
    op.drop_table('dataset_files')
    # ### end Alembic commands ###
