"""empty message

Revision ID: b335b7b18037
Revises: a584a36010be
Create Date: 2020-05-13 02:43:27.776194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b335b7b18037'
down_revision = 'a584a36010be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('w2v_models', sa.Column('iterations', sa.Integer(), nullable=True))
    op.add_column('w2v_models', sa.Column('min_count', sa.Integer(), nullable=True))
    op.add_column('w2v_models', sa.Column('window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('w2v_models', 'window')
    op.drop_column('w2v_models', 'min_count')
    op.drop_column('w2v_models', 'iterations')
    # ### end Alembic commands ###
